### ISSUE TITLE
issue with modelSelection.json

### ISSUE THREAD

**Issue by zednaked** [codestoryai/binaries#8]
After the today's update, when i try to use the chat, it says there is an issue with modelSelection.json. "No response from provider." . Im trying to use the claude sonnet shipped with the IDE.

**Comment by theskcd** [comment]
hey! Apologies but a packaging issue slipped from our side causing the regression ... we will push a fix but can only do so in 2 hours (the releases are gated by time)

**Comment by blistovmhz** [comment]
Same issue for me just now with the most recent release. We don't seem to have any way to login?

**Comment by theskcd** [comment]
The latest version fixes the issue. Try downloading it from the website. Apologies again for the mess

**Comment by Srikanthb4u** [comment]
There is an issue with your `modelSelection.json`: "Unable to validate model configuration. This is likely an issue at our end. Please let us know!"

**Comment by zednaked** [comment]
it got patched, just now
